//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceSimulator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_it2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_it2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaceSimulator.Properties.Resources.it2", typeof(Resources_it2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bambina Pesca.
        /// </summary>
        internal static string Baby_Peach {
            get {
                return ResourceManager.GetString("Baby Peach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bambina Margherita.
        /// </summary>
        internal static string BabyDaisy {
            get {
                return ResourceManager.GetString("BabyDaisy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bambino Luigi.
        /// </summary>
        internal static string BabyLuigi {
            get {
                return ResourceManager.GetString("BabyLuigi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bambino Mario.
        /// </summary>
        internal static string BabyMario {
            get {
                return ResourceManager.GetString("BabyMario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uccello.
        /// </summary>
        internal static string Birdo {
            get {
                return ResourceManager.GetString("Birdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bowser.
        /// </summary>
        internal static string Bowser {
            get {
                return ResourceManager.GetString("Bowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bowser Giuniore.
        /// </summary>
        internal static string BowserJunior {
            get {
                return ResourceManager.GetString("BowserJunior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margherita.
        /// </summary>
        internal static string Daisy {
            get {
                return ResourceManager.GetString("Daisy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diddy Kong.
        /// </summary>
        internal static string DiddyKong {
            get {
                return ResourceManager.GetString("DiddyKong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asino Kong.
        /// </summary>
        internal static string DonkeyKong {
            get {
                return ResourceManager.GetString("DonkeyKong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ossa Asciutte.
        /// </summary>
        internal static string DryBones {
            get {
                return ResourceManager.GetString("DryBones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bowser Asciutto.
        /// </summary>
        internal static string DryBowser {
            get {
                return ResourceManager.GetString("DryBowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kong Funky.
        /// </summary>
        internal static string FunkyKong {
            get {
                return ResourceManager.GetString("FunkyKong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re Boo.
        /// </summary>
        internal static string King_Boo {
            get {
                return ResourceManager.GetString("King Boo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koopa Troopa.
        /// </summary>
        internal static string KoopaTroopa {
            get {
                return ResourceManager.GetString("KoopaTroopa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luigi.
        /// </summary>
        internal static string Luigi {
            get {
                return ResourceManager.GetString("Luigi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circuito di Luigi.
        /// </summary>
        internal static string Luigi_Circuit {
            get {
                return ResourceManager.GetString("Luigi Circuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funghi.
        /// </summary>
        internal static string Mushroom {
            get {
                return ResourceManager.GetString("Mushroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesca.
        /// </summary>
        internal static string Peach {
            get {
                return ResourceManager.GetString("Peach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosalina.
        /// </summary>
        internal static string Rosalina {
            get {
                return ResourceManager.GetString("Rosalina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rospo.
        /// </summary>
        internal static string Toad {
            get {
                return ResourceManager.GetString("Toad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rospetta.
        /// </summary>
        internal static string Toadette {
            get {
                return ResourceManager.GetString("Toadette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waluigi.
        /// </summary>
        internal static string Waluigi {
            get {
                return ResourceManager.GetString("Waluigi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wario.
        /// </summary>
        internal static string Wario {
            get {
                return ResourceManager.GetString("Wario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yoshi.
        /// </summary>
        internal static string Yoshi {
            get {
                return ResourceManager.GetString("Yoshi", resourceCulture);
            }
        }
    }
}
