//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Controller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Peach.
        /// </summary>
        public static string Baby_Peach {
            get {
                return ResourceManager.GetString("Baby Peach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Daisy.
        /// </summary>
        public static string BabyDaisy {
            get {
                return ResourceManager.GetString("BabyDaisy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Luigi.
        /// </summary>
        public static string BabyLuigi {
            get {
                return ResourceManager.GetString("BabyLuigi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Mario.
        /// </summary>
        public static string BabyMario {
            get {
                return ResourceManager.GetString("BabyMario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition:.
        /// </summary>
        public static string CompetitionTitle {
            get {
                return ResourceManager.GetString("CompetitionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string HeaderItemName {
            get {
                return ResourceManager.GetString("HeaderItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string HeaderItemPoints {
            get {
                return ResourceManager.GetString("HeaderItemPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string LanguageItalian {
            get {
                return ResourceManager.GetString("LanguageItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string Letter_of_BabyDaisy {
            get {
                return ResourceManager.GetString("Letter of BabyDaisy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l.
        /// </summary>
        public static string Letter_of_BabyLuigi {
            get {
                return ResourceManager.GetString("Letter of BabyLuigi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string Letter_of_BabyMario {
            get {
                return ResourceManager.GetString("Letter of BabyMario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p.
        /// </summary>
        public static string Letter_of_BabyPeach {
            get {
                return ResourceManager.GetString("Letter of BabyPeach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string Letter_of_Birdo {
            get {
                return ResourceManager.GetString("Letter of Birdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string Letter_of_Bowser {
            get {
                return ResourceManager.GetString("Letter of Bowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b.
        /// </summary>
        public static string Letter_of_BowserJunior {
            get {
                return ResourceManager.GetString("Letter of BowserJunior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♠.
        /// </summary>
        public static string Letter_of_Daisy {
            get {
                return ResourceManager.GetString("Letter of Daisy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♣.
        /// </summary>
        public static string Letter_of_DiddyKong {
            get {
                return ResourceManager.GetString("Letter of DiddyKong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✶.
        /// </summary>
        public static string Letter_of_DonkeyKong {
            get {
                return ResourceManager.GetString("Letter of DonkeyKong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string Letter_of_DryBones {
            get {
                return ResourceManager.GetString("Letter of DryBones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string Letter_of_DryBowser {
            get {
                return ResourceManager.GetString("Letter of DryBowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        public static string Letter_of_FunkyKong {
            get {
                return ResourceManager.GetString("Letter of FunkyKong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string Letter_of_KingBoo {
            get {
                return ResourceManager.GetString("Letter of KingBoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        public static string Letter_of_KoopaTroopa {
            get {
                return ResourceManager.GetString("Letter of KoopaTroopa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string Letter_of_Luigi {
            get {
                return ResourceManager.GetString("Letter of Luigi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string Letter_of_Mario {
            get {
                return ResourceManager.GetString("Letter of Mario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        public static string Letter_of_Peach {
            get {
                return ResourceManager.GetString("Letter of Peach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string Letter_of_Rosalina {
            get {
                return ResourceManager.GetString("Letter of Rosalina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string Letter_of_Toad {
            get {
                return ResourceManager.GetString("Letter of Toad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t.
        /// </summary>
        public static string Letter_of_Toadette {
            get {
                return ResourceManager.GetString("Letter of Toadette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string Letter_of_Waluigi {
            get {
                return ResourceManager.GetString("Letter of Waluigi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w.
        /// </summary>
        public static string Letter_of_Wario {
            get {
                return ResourceManager.GetString("Letter of Wario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Letter_of_Yoshi {
            get {
                return ResourceManager.GetString("Letter of Yoshi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition.
        /// </summary>
        public static string MenuCompetition {
            get {
                return ResourceManager.GetString("MenuCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant Statistics.
        /// </summary>
        public static string MenuParticipantStatistics {
            get {
                return ResourceManager.GetString("MenuParticipantStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race Statistics.
        /// </summary>
        public static string MenuRaceStatistics {
            get {
                return ResourceManager.GetString("MenuRaceStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mushroom.
        /// </summary>
        public static string Mushroom {
            get {
                return ResourceManager.GetString("Mushroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Up:.
        /// </summary>
        public static string NextTrackTitle {
            get {
                return ResourceManager.GetString("NextTrackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 point.
        /// </summary>
        public static string Points_1 {
            get {
                return ResourceManager.GetString("Points_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} points.
        /// </summary>
        public static string PointsFormatter {
            get {
                return ResourceManager.GetString("PointsFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track:.
        /// </summary>
        public static string TrackTitle {
            get {
                return ResourceManager.GetString("TrackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mario Kart.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
