//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Controller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Peach.
        /// </summary>
        public static string Baby_Peach {
            get {
                return ResourceManager.GetString("Baby Peach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Daisy.
        /// </summary>
        public static string BabyDaisy {
            get {
                return ResourceManager.GetString("BabyDaisy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Luigi.
        /// </summary>
        public static string BabyLuigi {
            get {
                return ResourceManager.GetString("BabyLuigi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Mario.
        /// </summary>
        public static string BabyMario {
            get {
                return ResourceManager.GetString("BabyMario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mushroom.
        /// </summary>
        public static string Mushroom {
            get {
                return ResourceManager.GetString("Mushroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mario Kart.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
